apiVersion: v1
kind: Pod
metadata:
  name: hellok8s-pod
spce:
  containers:
    - name: hellok8s-container
      image: registry.cn-hangzhou.aliyuncs.com/malyue/hellok8s:v3
      env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: hellok8s-config
              key: DB_URL